config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'                        #ルートパスの指定
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #未ログイン時はログインページに遷移する
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to 'group/1/messages', notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :'グループ名', class:'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class:'chat-group-form__input', placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    /
      <div class='chat-group-form__field--left'>
      <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
      </div>
      <div class='chat-group-form__field--right'>
      <div class='chat-group-form__search clearfix'>
      <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
      </div>
      <div id='user-search-result'></div>
      </div>
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :'チャットメンバー', class:'chat-group-form__label'
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all,:id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div id='chat-group-users'>
        <div class='chat-group-user clearfix' id='chat-group-user-22'>
        <input name='chat_group[user_ids][]' type='hidden' value='22'>
        <p class='chat-group-user__name'>seo_kyohei</p>
        </div>
        </div>
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class:'chat-group-form__action-btn'

app/views/groups/_sidebar.html.haml
.sideBar
  .header-sideBar
    = current_user.name
    = link_to edit_user_path(current_user) do
      = fa_icon 'cog', class: 'icon'
    = link_to new_group_path do
      = fa_icon 'pencil-square-o', class: 'icon'
  .groupList
    .group
      - current_user.groups.each do |group|
        = link_to group_messages_path(group), class: 'group_link' do
          .group__name
            = group.name
          .group__newComment
            メッセージはまだありません。

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper

  = render 'sidebar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %header
    %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.message
  .contents
    .header
      .header__group
        = @group.name
      .header__button
        = link_to 'Edit', 'groups/1/edit', class: 'edit__button'
      .header__member
        Members：
    .main
      .main__commentList
        .main__commentList__name
          name1
        .main__commentList__postTime
          2019/2/7 06:27:14
        .main__commentList__comment
          今から取り組み予定
        .main__commentList__name
          name2
        .main__commentList__postTime
          2019/2/7 08:27:14
        .main__commentList__comment
          テストコメント１
    .form
      .form__text
        %input{ type: 'text', class: 'comment__form', placeholder: "メッセージを入力してください" }
      .form__mask
        %label.form__mask__icon{for: "message_image"}
          %i.fa.fa-image
          = file_field :message, :image, class: 'hidden'
      .form__button
        = link_to 'Send', '', class: 'send__button'

app/views/messages/index.html.haml
= render partial: "/groups/sidebar", class: 'tst'
.contents
  .header
    .header__group
      sampleグループ
    .header__button
      = link_to 'Edit', 'groups/1/edit', class: 'edit__button'
    .header__member
      Members：seo neko

  .main
    .main__commentList
      .main__commentList__name
        name1
      .main__commentList__postTime
        2019/2/7 06:27:14
      .main__commentList__comment
        command Enterで送信したい感ある
      .main__commentList__name
        name2
      .main__commentList__postTime
        2019/2/7 08:27:14
      .main__commentList__comment
        お腹すいた
  .form
    .form__text
      %input{ type: 'text', class: 'comment__form', placeholder: "type a message" }
    .form__mask
      %label.form__mask__icon{for: "message_image"}
        %i.fa.fa-image
        = file_field :message, :image, class: 'hidden'
    .form__button
      = link_to 'Send', '', class: 'send__button'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
          .actions
            = f.submit "Update", class: 'btn'